// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sf376_Mission6.Models;

namespace Sf376_Mission6.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230209204736_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Sf376_Mission6.Models.ApplicationResponse", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            Title = "The Agengers",
                            Category = "Action/Adventure",
                            Director = "Joss Whedon",
                            Edited = false,
                            LentTo = "",
                            Notes = "This is a classic",
                            Rating = "PG-13",
                            Year = 2012
                        },
                        new
                        {
                            Title = "Batman Begins",
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "This is my favorite!",
                            Rating = "PG-13",
                            Year = 2005
                        },
                        new
                        {
                            Title = "Lord of the Rings: The Return of the King",
                            Category = "Action/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "",
                            Notes = "I had no idea this was from 2003 haha",
                            Rating = "PG-13",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
